### ISSUE TITLE
macOS Sierra 10.12.4 Failed to mount the InstallESD.dmg

### ISSUE THREAD

**Issue by vitalymak** [geerlingguy/macos-virtualbox-vm#25] opened 2017-04-28 11:23 UTC
Downloaded 2017-04-28 macOS Sierra:

```sh
vit:tmp vitaly$ ./prepare-iso.sh
hdiutil: detach: only a single device name can be specified
Usage:	hdiutil detach [options] <devname>
	hdiutil detach -help

Mount the installer image
-----------------------------------------------------------
$ hdiutil attach /Applications/Install macOS Sierra.app/Contents/SharedSupport/InstallESD.dmg -noverify -nobrowse -mountpoint /Volumes/install_app
hdiutil: attach failed - Resource busy
Failed to mount the InstallESD.dmg from the instaler at Install macOS Sierra.app.  Exiting. (1)
```

Just in case:

```
vit:tmp vitaly$ cat /Applications/Install\ macOS\ Sierra.app/Contents/version.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildVersion</key>
	<string>55</string>
	<key>CFBundleShortVersionString</key>
	<string>12.4.06</string>
	<key>CFBundleVersion</key>
	<string>12406</string>
	<key>ProjectName</key>
	<string>InstallAssistant</string>
	<key>SourceVersion</key>
	<string>842012000000000</string>
</dict>
</plist>
```

**Comment by vitalymak** [comment] 2017-04-28 11:47
Actually it's related only to _hdiutil: attach failed - Resource busy_

solved by 
```
hdiutil info | grep /dev/disk | grep partition | cut -f 1 | xargs hdiutil detach
```

Maybe add this line before installation?

**Comment by geerlingguy** [comment] 2017-05-05 16:46
Also, see upstream bug: https://www.virtualbox.org/ticket/16644

**Comment by vitalymak** [comment] 2017-05-05 17:46
Yep, but upstream issue is actually related to https://github.com/geerlingguy/macos-virtualbox-vm/issues/24 bug 😀

**Comment by geerlingguy** [comment] 2017-05-05 18:05
Gah, I'm confusing my issues now :P

**Comment by geerlingguy** [comment] 2018-08-15 18:15
I believe this was fixed by one of the other recent commits... I can't reproduce the error anymore.

**Closed by geerlingguy** 2018-08-15 18:15 UTC
Labels: bug
